import { CountryData } from './types';

// Data sources approximation: UNDP, World Bank, UNODC, CIA World Factbook (2022-2024 Estimates)
export const COUNTRIES: CountryData[] = [
  // --- América do Sul / South America ---
  { name: "Brasil", name_en: "Brazil", hdi: 0.760, population: 216400000, homicideRate: 22.3, continent: "América do Sul", continent_en: "South America", flagEmoji: "🇧🇷", language: "Português", language_en: "Portuguese", famousPlayer: "Pelé / Neymar", independenceYear: "1822" },
  { name: "Argentina", name_en: "Argentina", hdi: 0.849, population: 46600000, homicideRate: 4.6, continent: "América do Sul", continent_en: "South America", flagEmoji: "🇦🇷", language: "Espanhol", language_en: "Spanish", famousPlayer: "Lionel Messi", independenceYear: "1816" },
  { name: "Colômbia", name_en: "Colombia", hdi: 0.752, population: 52000000, homicideRate: 25.3, continent: "América do Sul", continent_en: "South America", flagEmoji: "🇨🇴", language: "Espanhol", language_en: "Spanish", famousPlayer: "Carlos Valderrama", independenceYear: "1810" },
  { name: "Chile", name_en: "Chile", hdi: 0.860, population: 19600000, homicideRate: 6.7, continent: "América do Sul", continent_en: "South America", flagEmoji: "🇨🇱", language: "Espanhol", language_en: "Spanish", famousPlayer: "Arturo Vidal", independenceYear: "1818" },
  { name: "Peru", name_en: "Peru", hdi: 0.762, population: 34300000, homicideRate: 8.7, continent: "América do Sul", continent_en: "South America", flagEmoji: "🇵🇪", language: "Espanhol", language_en: "Spanish", famousPlayer: "Paolo Guerrero", independenceYear: "1821" },
  { name: "Uruguai", name_en: "Uruguay", hdi: 0.830, population: 3400000, homicideRate: 11.2, continent: "América do Sul", continent_en: "South America", flagEmoji: "🇺🇾", language: "Espanhol", language_en: "Spanish", famousPlayer: "Luis Suárez", independenceYear: "1825" },
  { name: "Equador", name_en: "Ecuador", hdi: 0.765, population: 18300000, homicideRate: 44.5, continent: "América do Sul", continent_en: "South America", flagEmoji: "🇪🇨", language: "Espanhol", language_en: "Spanish", famousPlayer: "Antonio Valencia", independenceYear: "1809" },
  { name: "Venezuela", name_en: "Venezuela", hdi: 0.690, population: 29000000, homicideRate: 26.8, continent: "América do Sul", continent_en: "South America", flagEmoji: "🇻🇪", language: "Espanhol", language_en: "Spanish", famousPlayer: "Salomón Rondón", independenceYear: "1811" },

  // --- América do Norte e Central / North & Central America ---
  { name: "Estados Unidos", name_en: "United States", hdi: 0.927, population: 334900000, homicideRate: 6.4, continent: "América do Norte", continent_en: "North America", flagEmoji: "🇺🇸", language: "Inglês", language_en: "English", famousPlayer: "Christian Pulisic", independenceYear: "1776" },
  { name: "Canadá", name_en: "Canada", hdi: 0.935, population: 40000000, homicideRate: 2.3, continent: "América do Norte", continent_en: "North America", flagEmoji: "🇨🇦", language: "Inglês / Francês", language_en: "English / French", famousPlayer: "Alphonso Davies", independenceYear: "1867" },
  { name: "México", name_en: "Mexico", hdi: 0.758, population: 128500000, homicideRate: 26.1, continent: "América do Norte", continent_en: "North America", flagEmoji: "🇲🇽", language: "Espanhol", language_en: "Spanish", famousPlayer: "Hugo Sánchez", independenceYear: "1810" },
  { name: "Cuba", name_en: "Cuba", hdi: 0.764, population: 11000000, homicideRate: 4.4, continent: "América Central", continent_en: "Central America", flagEmoji: "🇨🇺", language: "Espanhol", language_en: "Spanish", famousPlayer: "Javier Sotomayor (Atleta)", independenceYear: "1902" },
  { name: "Jamaica", name_en: "Jamaica", hdi: 0.706, population: 2800000, homicideRate: 53.3, continent: "América Central", continent_en: "Central America", flagEmoji: "🇯🇲", language: "Inglês", language_en: "English", famousPlayer: "Usain Bolt (Atleta)", independenceYear: "1962" },
  { name: "Costa Rica", name_en: "Costa Rica", hdi: 0.806, population: 5200000, homicideRate: 12.2, continent: "América Central", continent_en: "Central America", flagEmoji: "🇨🇷", language: "Espanhol", language_en: "Spanish", famousPlayer: "Keylor Navas", independenceYear: "1821" },
  { name: "El Salvador", name_en: "El Salvador", hdi: 0.675, population: 6300000, homicideRate: 7.8, continent: "América Central", continent_en: "Central America", flagEmoji: "🇸🇻", language: "Espanhol", language_en: "Spanish", famousPlayer: "Mágico González", independenceYear: "1841" },

  // --- Europa / Europe ---
  { name: "Noruega", name_en: "Norway", hdi: 0.966, population: 5500000, homicideRate: 0.5, continent: "Europa", continent_en: "Europe", flagEmoji: "🇳🇴", language: "Norueguês", language_en: "Norwegian", famousPlayer: "Erling Haaland", independenceYear: "1905" },
  { name: "Alemanha", name_en: "Germany", hdi: 0.950, population: 84400000, homicideRate: 0.8, continent: "Europa", continent_en: "Europe", flagEmoji: "🇩🇪", language: "Alemão", language_en: "German", famousPlayer: "Franz Beckenbauer", independenceYear: "1871" },
  { name: "Reino Unido", name_en: "United Kingdom", hdi: 0.940, population: 67700000, homicideRate: 1.0, continent: "Europa", continent_en: "Europe", flagEmoji: "🇬🇧", language: "Inglês", language_en: "English", famousPlayer: "David Beckham", independenceYear: "1066 (Unif.)", independenceYear_en: "1066 (Unif.)" },
  { name: "França", name_en: "France", hdi: 0.910, population: 68000000, homicideRate: 1.1, continent: "Europa", continent_en: "Europe", flagEmoji: "🇫🇷", language: "Francês", language_en: "French", famousPlayer: "Zinedine Zidane", independenceYear: "843 (Verdun)", independenceYear_en: "843 (Verdun)" },
  { name: "Itália", name_en: "Italy", hdi: 0.906, population: 58900000, homicideRate: 0.5, continent: "Europa", continent_en: "Europe", flagEmoji: "🇮🇹", language: "Italiano", language_en: "Italian", famousPlayer: "Roberto Baggio", independenceYear: "1861" },
  { name: "Espanha", name_en: "Spain", hdi: 0.911, population: 48000000, homicideRate: 0.6, continent: "Europa", continent_en: "Europe", flagEmoji: "🇪🇸", language: "Espanhol", language_en: "Spanish", famousPlayer: "Andrés Iniesta", independenceYear: "1492 (Unif.)", independenceYear_en: "1492 (Unif.)" },
  { name: "Portugal", name_en: "Portugal", hdi: 0.874, population: 10400000, homicideRate: 0.8, continent: "Europa", continent_en: "Europe", flagEmoji: "🇵🇹", language: "Português", language_en: "Portuguese", famousPlayer: "Cristiano Ronaldo", independenceYear: "1143" },
  { name: "Rússia", name_en: "Russia", hdi: 0.821, population: 144400000, homicideRate: 6.8, continent: "Europa/Ásia", continent_en: "Europe/Asia", flagEmoji: "🇷🇺", language: "Russo", language_en: "Russian", famousPlayer: "Lev Yashin", independenceYear: "1991 (Federação)", independenceYear_en: "1991 (Federation)" },
  { name: "Ucrânia", name_en: "Ukraine", hdi: 0.734, population: 37000000, homicideRate: 6.2, continent: "Europa", continent_en: "Europe", flagEmoji: "🇺🇦", language: "Ucraniano", language_en: "Ukrainian", famousPlayer: "Andriy Shevchenko", independenceYear: "1991" },
  { name: "Suíça", name_en: "Switzerland", hdi: 0.967, population: 8800000, homicideRate: 0.5, continent: "Europa", continent_en: "Europe", flagEmoji: "🇨🇭", language: "Alemão/Francês/Ital.", language_en: "German/French/Ital.", famousPlayer: "Xherdan Shaqiri", independenceYear: "1291" },
  { name: "Holanda", name_en: "Netherlands", hdi: 0.946, population: 17800000, homicideRate: 0.6, continent: "Europa", continent_en: "Europe", flagEmoji: "🇳🇱", language: "Holandês", language_en: "Dutch", famousPlayer: "Johan Cruyff", independenceYear: "1581" },
  { name: "Bélgica", name_en: "Belgium", hdi: 0.942, population: 11700000, homicideRate: 1.1, continent: "Europa", continent_en: "Europe", flagEmoji: "🇧🇪", language: "Holandês/Francês", language_en: "Dutch/French", famousPlayer: "Kevin De Bruyne", independenceYear: "1830" },
  { name: "Suécia", name_en: "Sweden", hdi: 0.952, population: 10500000, homicideRate: 1.1, continent: "Europa", continent_en: "Europe", flagEmoji: "🇸🇪", language: "Sueco", language_en: "Swedish", famousPlayer: "Zlatan Ibrahimović", independenceYear: "1523" },
  { name: "Polônia", name_en: "Poland", hdi: 0.881, population: 36600000, homicideRate: 0.7, continent: "Europa", continent_en: "Europe", flagEmoji: "🇵🇱", language: "Polonês", language_en: "Polish", famousPlayer: "Robert Lewandowski", independenceYear: "1918" },
  { name: "Grécia", name_en: "Greece", hdi: 0.893, population: 10300000, homicideRate: 0.8, continent: "Europa", continent_en: "Europe", flagEmoji: "🇬🇷", language: "Grego", language_en: "Greek", famousPlayer: "Giannis Antetokounmpo (NBA)", independenceYear: "1821" },

  // --- Ásia / Asia ---
  { name: "Japão", name_en: "Japan", hdi: 0.920, population: 123300000, homicideRate: 0.2, continent: "Ásia", continent_en: "Asia", flagEmoji: "🇯🇵", language: "Japonês", language_en: "Japanese", famousPlayer: "Hidetoshi Nakata", independenceYear: "660 a.C.", independenceYear_en: "660 BC" },
  { name: "China", name_en: "China", hdi: 0.788, population: 1425000000, homicideRate: 0.5, continent: "Ásia", continent_en: "Asia", flagEmoji: "🇨🇳", language: "Mandarim", language_en: "Mandarin", famousPlayer: "Wu Lei", independenceYear: "221 a.C. (Unif.)", independenceYear_en: "221 BC (Unif.)" },
  { name: "Índia", name_en: "India", hdi: 0.644, population: 1428000000, homicideRate: 2.9, continent: "Ásia", continent_en: "Asia", flagEmoji: "🇮🇳", language: "Hindi / Inglês", language_en: "Hindi / English", famousPlayer: "Sunil Chhetri", independenceYear: "1947" },
  { name: "Coreia do Sul", name_en: "South Korea", hdi: 0.929, population: 51700000, homicideRate: 0.5, continent: "Ásia", continent_en: "Asia", flagEmoji: "🇰🇷", language: "Coreano", language_en: "Korean", famousPlayer: "Son Heung-min", independenceYear: "1948" },
  { name: "Indonésia", name_en: "Indonesia", hdi: 0.713, population: 277500000, homicideRate: 0.4, continent: "Ásia", continent_en: "Asia", flagEmoji: "🇮🇩", language: "Indonésio", language_en: "Indonesian", famousPlayer: "Bambang Pamungkas", independenceYear: "1945" },
  { name: "Arábia Saudita", name_en: "Saudi Arabia", hdi: 0.875, population: 36000000, homicideRate: 0.8, continent: "Ásia", continent_en: "Asia", flagEmoji: "🇸🇦", language: "Árabe", language_en: "Arabic", famousPlayer: "Salem Al-Dawsari", independenceYear: "1932" },
  { name: "Turquia", name_en: "Turkey", hdi: 0.855, population: 85300000, homicideRate: 2.5, continent: "Ásia/Europa", continent_en: "Asia/Europe", flagEmoji: "🇹🇷", language: "Turco", language_en: "Turkish", famousPlayer: "Hakan Şükür", independenceYear: "1923" },
  { name: "Irã", name_en: "Iran", hdi: 0.780, population: 89000000, homicideRate: 2.2, continent: "Ásia", continent_en: "Asia", flagEmoji: "🇮🇷", language: "Persa", language_en: "Persian", famousPlayer: "Ali Daei", independenceYear: "1979 (Rep. Islâmica)", independenceYear_en: "1979 (Islamic Rep.)" },
  { name: "Vietnã", name_en: "Vietnam", hdi: 0.726, population: 99500000, homicideRate: 1.5, continent: "Ásia", continent_en: "Asia", flagEmoji: "🇻🇳", language: "Vietnamita", language_en: "Vietnamese", famousPlayer: "Lê Công Vinh", independenceYear: "1945" },
  { name: "Tailândia", name_en: "Thailand", hdi: 0.803, population: 71800000, homicideRate: 2.6, continent: "Ásia", continent_en: "Asia", flagEmoji: "🇹🇭", language: "Tailandês", language_en: "Thai", famousPlayer: "Chanathip Songkrasin", independenceYear: "1238 (Reino)", independenceYear_en: "1238 (Kingdom)" },
  { name: "Paquistão", name_en: "Pakistan", hdi: 0.540, population: 240500000, homicideRate: 3.8, continent: "Ásia", continent_en: "Asia", flagEmoji: "🇵🇰", language: "Urdu / Inglês", language_en: "Urdu / English", famousPlayer: "Imran Khan (Cricket)", independenceYear: "1947" },
  { name: "Filipinas", name_en: "Philippines", hdi: 0.710, population: 117300000, homicideRate: 4.3, continent: "Ásia", continent_en: "Asia", flagEmoji: "🇵🇭", language: "Filipino / Inglês", language_en: "Filipino / English", famousPlayer: "Manny Pacquiao (Boxe)", independenceYear: "1898" },
  { name: "Israel", name_en: "Israel", hdi: 0.915, population: 9700000, homicideRate: 1.6, continent: "Ásia", continent_en: "Asia", flagEmoji: "🇮🇱", language: "Hebraico", language_en: "Hebrew", famousPlayer: "Yossi Benayoun", independenceYear: "1948" },

  // --- África / Africa ---
  { name: "Nigéria", name_en: "Nigeria", hdi: 0.548, population: 223800000, homicideRate: 22.0, continent: "África", continent_en: "Africa", flagEmoji: "🇳🇬", language: "Inglês", language_en: "English", famousPlayer: "Jay-Jay Okocha", independenceYear: "1960" },
  { name: "África do Sul", name_en: "South Africa", hdi: 0.717, population: 60400000, homicideRate: 41.5, continent: "África", continent_en: "Africa", flagEmoji: "🇿🇦", language: "11 idiomas oficiais", language_en: "11 official languages", famousPlayer: "Benni McCarthy", independenceYear: "1910" },
  { name: "Egito", name_en: "Egypt", hdi: 0.728, population: 112700000, homicideRate: 1.3, continent: "África", continent_en: "Africa", flagEmoji: "🇪🇬", language: "Árabe", language_en: "Arabic", famousPlayer: "Mohamed Salah", independenceYear: "1922" },
  { name: "Marrocos", name_en: "Morocco", hdi: 0.698, population: 37800000, homicideRate: 1.3, continent: "África", continent_en: "Africa", flagEmoji: "🇲🇦", language: "Árabe / Berbere", language_en: "Arabic / Berber", famousPlayer: "Achraf Hakimi", independenceYear: "1956" },
  { name: "Gana", name_en: "Ghana", hdi: 0.602, population: 34000000, homicideRate: 2.1, continent: "África", continent_en: "Africa", flagEmoji: "🇬🇭", language: "Inglês", language_en: "English", famousPlayer: "Abedi Pele", independenceYear: "1957" },
  { name: "Quênia", name_en: "Kenya", hdi: 0.601, population: 55000000, homicideRate: 5.3, continent: "África", continent_en: "Africa", flagEmoji: "🇰🇪", language: "Suaíli / Inglês", language_en: "Swahili / English", famousPlayer: "Eliud Kipchoge (Maratona)", independenceYear: "1963" },
  { name: "Etiópia", name_en: "Ethiopia", hdi: 0.498, population: 126500000, homicideRate: 8.8, continent: "África", continent_en: "Africa", flagEmoji: "🇪🇹", language: "Amárico", language_en: "Amharic", famousPlayer: "Haile Gebrselassie (Atleta)", independenceYear: "Antiguidade", independenceYear_en: "Antiquity" },
  { name: "Senegal", name_en: "Senegal", hdi: 0.517, population: 18000000, homicideRate: 0.3, continent: "África", continent_en: "Africa", flagEmoji: "🇸🇳", language: "Francês", language_en: "French", famousPlayer: "Sadio Mané", independenceYear: "1960" },
  { name: "Camarões", name_en: "Cameroon", hdi: 0.587, population: 28600000, homicideRate: 4.5, continent: "África", continent_en: "Africa", flagEmoji: "🇨🇲", language: "Francês / Inglês", language_en: "French / English", famousPlayer: "Samuel Eto'o", independenceYear: "1960" },
  { name: "Costa do Marfim", name_en: "Ivory Coast", hdi: 0.534, population: 29000000, homicideRate: 11.6, continent: "África", continent_en: "Africa", flagEmoji: "🇨🇮", language: "Francês", language_en: "French", famousPlayer: "Didier Drogba", independenceYear: "1960" },

  // --- Oceania ---
  { name: "Austrália", name_en: "Australia", hdi: 0.946, population: 26500000, homicideRate: 0.8, continent: "Oceania", continent_en: "Oceania", flagEmoji: "🇦🇺", language: "Inglês", language_en: "English", famousPlayer: "Tim Cahill", independenceYear: "1901" },
  { name: "Nova Zelândia", name_en: "New Zealand", hdi: 0.939, population: 5200000, homicideRate: 0.7, continent: "Oceania", continent_en: "Oceania", flagEmoji: "🇳🇿", language: "Inglês / Maori", language_en: "English / Maori", famousPlayer: "Jonah Lomu (Rugby)", independenceYear: "1907" }
];